version: 2
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          name: npm install
          command: npm i
      - run:
          name: pre-publish
          command: npm run vscode:prepublish
  test:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - run:
          name: Test
          command: npm test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
